Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # =========================
  # VM 2 - HAProxy
  # =========================
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "10.0.10.10"
    haproxy.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    haproxy.vm.provision "shell", path: "provision/common.sh"
    haproxy.vm.provision "shell", path: "provision/haproxy.sh"
  end

  # =========================
  # VM 3 - App
  # =========================
  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "10.0.10.20"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    app.vm.provision "shell", path: "provision/common.sh"
    app.vm.provision "shell", path: "provision/app.sh"
  end

  # =========================
  # VM 5 - Monitor
  # =========================
  config.vm.define "monitor" do |monitor|
    monitor.vm.hostname = "monitor"
    monitor.vm.network "private_network", ip: "10.0.10.30"
    monitor.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    monitor.vm.provision "shell", path: "provision/common.sh"
    monitor.vm.provision "shell", path: "provision/monitor.sh"
  end

end
